CREATE TABLE `journal`
(
    `id`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
    `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME     NULL     DEFAULT NULL,
    `version`     SMALLINT(6)  NOT NULL,
    `active`      TINYINT(6)   NOT NULL DEFAULT 1,
    `external_id` VARCHAR(50)  NOT NULL,
    `title`       VARCHAR(255) NOT NULL,
    `content`     TEXT         NOT NULL,
    `mood`        VARCHAR(50),
    `user_id`     VARCHAR(50)  NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `external_id_uq_idx` UNIQUE (`external_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

-- Spring Session JDBC tables for MySQL
CREATE TABLE IF NOT EXISTS `SPRING_SESSION` (
    `PRIMARY_ID` CHAR(36) NOT NULL,
    `SESSION_ID` CHAR(36) NOT NULL,
    `CREATION_TIME` BIGINT NOT NULL,
    `LAST_ACCESS_TIME` BIGINT NOT NULL,
    `MAX_INACTIVE_INTERVAL` INT NOT NULL,
    `EXPIRY_TIME` BIGINT NOT NULL,
    `PRINCIPAL_NAME` VARCHAR(100),
    PRIMARY KEY (`PRIMARY_ID`),
    UNIQUE KEY `SPRING_SESSION_IX1` (`SESSION_ID`),
    KEY `SPRING_SESSION_IX2` (`EXPIRY_TIME`),
    KEY `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `SPRING_SESSION_ATTRIBUTES` (
    `SESSION_PRIMARY_ID` CHAR(36) NOT NULL,
    `ATTRIBUTE_NAME` VARCHAR(200) NOT NULL,
    `ATTRIBUTE_BYTES` BLOB NOT NULL,
    PRIMARY KEY (`SESSION_PRIMARY_ID`, `ATTRIBUTE_NAME`),
    CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_PRIMARY_ID`) REFERENCES `SPRING_SESSION` (`PRIMARY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;